experiment_name: PLM_Sol_FineTuning_combined_high_1_5sigma_on_high_proline
num_epochs: 50
batch_size: 64
log_iterations: 10
patience: 2
optimizer_parameters:
  lr: 1.0e-4
target: sol
unknown_solubility: false
key_format: fasta_descriptor
exp_name: eval_combined_on_high_proline_test
train_embeddings: /home/david_nunn/PLM_Sol/fine_tuning_embeddings/combined_high_1_5sigma/train_emb/t5_embeddings/embeddings_file.h5
val_embeddings: /home/david_nunn/PLM_Sol/fine_tuning_embeddings/combined_high_1_5sigma/val_emb/t5_embeddings/embeddings_file.h5
test_embeddings: fine_tuning_embeddings/high_proline/merged_eval/embeddings_file.h5
test_remapping: fine_tuning_embeddings/high_proline/merged_eval/remapped_sequences_file.fasta
model_type: biLSTM_TextCNN
model_parameters:
  output_dim: 1
  dropout: 0.25
  kernel_size: 9
checkpoint: /home/david_nunn/PLM_Sol/outputs/finetune_combined_high_1_5sigma_fresh/models/model-best.t7
eval_on_test: true
