output_files_name: lacZ_inference
log_iterations: 100
n_draws: 1000
batch_size: 1
checkpoints_list:
- ./model_param/model_param.t7
embeddings: /home/david_nunn/PLM_Sol/plmsol_test/lacZ_emb/t5_embeddings/embeddings_file.h5
remapping: /home/david_nunn/PLM_Sol/plmsol_test/lacZ_emb/remapped_sequences_file.fasta
key_format: fasta_descriptor
