global:
  # Path to input sequences FASTA
  sequences_file: /home/david_nunn/PLM_Sol/plmsol_test/random_proteins_combined.fasta
  # Output directory prefix
  prefix: /home/david_nunn/PLM_Sol/plmsol_test/random_emb
