annotations_from_t5:
  depends_on: t5_embeddings
  protocol: la_prott5
  type: extract
global:
  prefix: /home/david_nunn/PLM_Sol/plmsol_test/test_dataset_emb
  sequences_file: /home/david_nunn/PLM_Sol/plmsol_test/test_dataset.fasta
t5_embeddings:
  half_precision: true
  half_precision_model: true
  protocol: prottrans_t5_xl_u50
  type: embed
